### ISSUE TITLE
Test fails with ENGINE=xelatex

### ISSUE THREAD

**Issue by louisabraham** [BinetReseau/polytechnique-pandoc#1]
```
make basic.pdf ENGINE=xelatex
pandoc basic.md --latex-engine=xelatex --template=../templates/x.latex -t latex -o basic.pdf
! Dimension too large.
<to be read again> 
                   b
l.68 ...phics[width=0.70000\textwidth]{normal.jpg}

pandoc: Error producing PDF
make: *** [basic.pdf] Error 43
```

on macOS Sierra
pandoc 1.19.1
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016/MacPorts 2016_3)

**Comment by w2ak** [comment]
* 21d18964e10fbaf6b141d877c13b35eafb198e2c

Solved by converting the picture from `.jpg` to `.jpg`. Note that this picture worked with lualatex and pdflatex, so this is more of a xelatex issue.

**Comment by louisabraham** [comment]
> converting the picture from .jpg to .jpg

could you clarify please?

**Comment by w2ak** [comment]
I literally did :

```sh
cp normal.jpg normal-bkp.jpg && rm normal.jpg
convert normal-bkp.jpg normal.jpg
make -B ENGINE=xelatex basic.pdf
```

And got a working pdf with no error. It just means the converted image was "cleaner" and xelatex was able to use it, whereas it wasn't able to use the previous version of the image which was accepted by lualatex and pdflatex.

**Comment by louisabraham** [comment]
It is strange. Thanks.
