### ISSUE TITLE
Quotations not supported

### ISSUE THREAD

**Issue by louisabraham** [BinetReseau/polytechnique-pandoc#2]
The syntax :

`> text here`

does not give the expected quotation style
> text here

**Comment by w2ak** [comment]
@louisabraham please attach the following files :
* a minimal Markdown file
* the pdf output with the default template (the one giving the expected style)
* the pdf output with my template

Because I just tested the default template from my `pandoc` and got the same style.
```sh
echo "> Testing quotations" >> basic.md
make TEMPLATE=default basic.pdf
```

**Comment by louisabraham** [comment]
My bad, I forgot that I changed the default pandoc template several monthes ago…

**Comment by w2ak** [comment]
You could send me the template you use to render your quotations, though.
